# -*- coding: utf-8 -*-
"""model.pkl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fvohxWFNhynOHGUDlHA6uVQmZ6vgHU0x
"""

import nltk

nltk.download('punkt_tab')

nltk.download('stopwords')

from nltk.corpus import stopwords

import re

text="An English paragraph is @#$%&*()234567889900 a self-contained unit of writing that develops a single central idea.It typically consists of a topic sentence, supporting sentences, and a concluding sentence. Breaking text into paragraphs organizes information and makes long-form writing visually digestible and coherent for the reader."

text=text.lower()

text= re.sub(r'\W',' ',text)

tokens=nltk.word_tokenize(text)

text_no_links = re.sub(r'http\S+|www\.\S+', '', text)

text_clean = re.sub(r'[^\w\s]', '', text_no_links)

print(text_clean)

clean_text = re.sub(r'[^a-zA-Z0-9\s]', '', text)

print(clean_text)

clean_text = re.sub(r'[^a-zA-Z\s]', '', text)
print(clean_text)

clean_text = re.sub(r'[^a-zA-Z\s]', '', text)
print(clean_text)

clean_text = re.sub(r'\s+', ' ', clean_text).strip()

print(clean_text)

import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

cleaned = [word for word in tokens if word not in stopwords.words('english')]

# Remove URLs
text = re.sub(r'http\S+|www\.\S+', '', text)

# Remove numbers
text = re.sub(r'\d+', '', text)

# Remove special characters (keep only letters and spaces)
text = re.sub(r'[^a-zA-Z\s]', '', text)

    # Remove extra spaces
text = re.sub(r'\s+', ' ', text).strip()

from nltk.stem import WordNetLemmatizer

from nltk.stem import PorterStemmer

from nltk.tokenize import word_tokenize

# Example text with potential duplicates after tokenization
example_text = "This is a test. This is only a test."

# Tokenize the text and convert to lowercase for consistent comparison
example_tokens = word_tokenize(example_text.lower())

print("Original tokens:", example_tokens)

# Remove duplicates by converting to a set and then back to a list
unique_tokens = list(set(example_tokens))

print("Unique tokens (duplicates removed):", unique_tokens)

nltk.download('punkt')

text = "NLP is fun and useful!"
tokens = word_tokenize(text)

print(tokens)

import spacy

nlp = spacy.load("en_core_web_sm")

text = "NLP is fun and useful!"
doc = nlp(text)

tokens = [token.text for token in doc]
print(tokens)

text = "NLP is fun and useful!"
tokens = text.split()

print(tokens)

import pandas as pd

# Example CSV file: 'data.csv' with columns 'text' and 'label'
df = pd.read_csv("/content/IMDB_Dataset.csv.zip")

df.info()

df.describe()

print(f"Initial shape of DataFrame: {df.shape}")

df.drop_duplicates(subset=['review'], inplace=True)

print(f"Shape of DataFrame after removing duplicates: {df.shape}")

df.drop_duplicates()

df.drop_duplicates()

"""### Tokenization and Stop Word Removal

Now that the reviews are cleaned, we will tokenize them (break them into individual words) and remove common English stop words. This helps to reduce noise and focus on more meaningful terms for analysis.
"""

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Ensure 'stopwords' is downloaded
try:
    stopwords.words('english')
except LookupError:
    nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

def tokenize_and_remove_stopwords(text):
    tokens = word_tokenize(text)
    filtered_tokens = [word for word in tokens if word not in stop_words]
    return filtered_tokens

df['processed_review'] = df['cleaned_review'].apply(tokenize_and_remove_stopwords)
print(df[['cleaned_review', 'processed_review']].head())

"""### Data Splitting for Model Training

To prepare the data for machine learning, we will split the dataset into training and testing sets. This allows us to train a model on one portion of the data and evaluate its performance on unseen data, preventing overfitting.
"""

from sklearn.model_selection import train_test_split

X = df['processed_review'] # Features (preprocessed text)
y = df['sentiment'] # Target variable

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

print("\nSentiment distribution in original dataset:\n", y.value_counts(normalize=True))
print("\nSentiment distribution in training set:\n", y_train.value_counts(normalize=True))
print("\nSentiment distribution in test set:\n", y_test.value_counts(normalize=True))

"""### Feature Extraction: TF-IDF Vectorization

To prepare the text data for machine learning algorithms, we need to convert the tokenized reviews into numerical features. TF-IDF (Term Frequency-Inverse Document Frequency) is a common technique that reflects how important a word is to a document in a collection or corpus.
"""

from sklearn.feature_extraction.text import TfidfVectorizer

# Join the processed review tokens back into strings for TF-IDF Vectorizer
X_train_str = X_train.apply(lambda x: ' '.join(x))
X_test_str = X_test.apply(lambda x: ' '.join(x))

# Initialize TF-IDF Vectorizer
# min_df ignores terms that have a document frequency strictly lower than the given threshold
# max_df ignores terms that have a document frequency strictly higher than the given threshold
tfidf_vectorizer = TfidfVectorizer(max_features=5000, min_df=5, max_df=0.8)

# Fit and transform the training data
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train_str)

# Transform the test data
X_test_tfidf = tfidf_vectorizer.transform(X_test_str)

print(f"Shape of X_train_tfidf: {X_train_tfidf.shape}")
print(f"Shape of X_test_tfidf: {X_test_tfidf.shape}")

"""### Model Training: Logistic Regression

With the text data vectorized, we can now train a classification model. Logistic Regression is a common and effective baseline model for binary classification tasks like sentiment analysis.
"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Initialize and train the Logistic Regression model
model = LogisticRegression(max_iter=1000, random_state=42)
model.fit(X_train_tfidf, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test_tfidf)

# Evaluate the model
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

"""### Lemmatization

Lemmatization is the process of grouping together the inflected forms of a word so they can be analyzed as a single item, identified by the word's lemma. This helps in reducing the dimensionality of the feature space and improving model performance by treating words like 'running', 'runs', and 'ran' as their base form 'run'.
"""

from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('omw-1.4')

lemmatizer = WordNetLemmatizer()

def lemmatize_tokens(tokens):
    return [lemmatizer.lemmatize(token) for token in tokens]

df['lemmatized_review'] = df['processed_review'].apply(lemmatize_tokens)
print(df[['processed_review', 'lemmatized_review']].head())

"""### Feature Extraction: CountVectorizer

Now, instead of TF-IDF, we will use `CountVectorizer` to transform the lemmatized text data into a matrix of token counts. This simple yet effective method counts the occurrences of each word in a document.
"""

from sklearn.feature_extraction.text import CountVectorizer

# Split the lemmatized reviews into training and testing sets
X_lemmatized = df['lemmatized_review']
y = df['sentiment']

X_train_lemmatized, X_test_lemmatized, y_train_cv, y_test_cv = train_test_split(X_lemmatized, y, test_size=0.2, random_state=42, stratify=y)

# Join the lemmatized tokens back into strings for CountVectorizer
X_train_lemmatized_str = X_train_lemmatized.apply(lambda x: ' '.join(x))
X_test_lemmatized_str = X_test_lemmatized.apply(lambda x: ' '.join(x))

# Initialize CountVectorizer
count_vectorizer = CountVectorizer(max_features=5000, min_df=5, max_df=0.8)

# Fit and transform the training data
X_train_counts = count_vectorizer.fit_transform(X_train_lemmatized_str)

# Transform the test data
X_test_counts = count_vectorizer.transform(X_test_lemmatized_str)

print(f"Shape of X_train_counts: {X_train_counts.shape}")
print(f"Shape of X_test_counts: {X_test_counts.shape}")

"""### Model Training with CountVectorizer Features

Now we will train a Logistic Regression model using the features generated by `CountVectorizer` and evaluate its performance.
"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Initialize and train the Logistic Regression model with CountVectorizer features
model_cv = LogisticRegression(max_iter=1000, random_state=42)
model_cv.fit(X_train_counts, y_train_cv)

# Make predictions on the test set
y_pred_cv = model_cv.predict(X_test_counts)

# Evaluate the model
print(f"Accuracy (CountVectorizer): {accuracy_score(y_test_cv, y_pred_cv):.4f}")
print("\nClassification Report (CountVectorizer):\n")
print(classification_report(y_test_cv, y_pred_cv))

"""### Confusion Matrix

A Confusion Matrix is a performance measurement for machine learning classification problems where the output can be two or more classes. It is a table with 4 different combinations of predicted and actual values. It helps to understand the types of errors made by the classifier (e.g., false positives, false negatives).
"""

import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

nltk.download('stopwords')

stemmer = PorterStemmer()
stop_words = set(stopwords.words('english'))

text = "Students are running 123 times!"

# Lowercase
text = text.lower()

# Remove numbers & special chars
text = re.sub(r'[^a-z\s]', '', text)

# Tokenize
words = text.split()

# Remove stopwords + stemming
cleaned = [stemmer.stem(word) for word in words if word not in stop_words]

print(cleaned)

import nltk
from nltk.corpus import stopwords

from sklearn.metrics import accuracy_score

Total_Predictions = len(y_test_cv)
Correct_Predictions = (y_test_cv == y_pred_cv).sum()

accuracy = Correct_Predictions / Total_Predictions

print(f"Total Predictions: {Total_Predictions}")
print(f"Correct Predictions: {Correct_Predictions}")
print(f"Calculated Accuracy: {accuracy:.4f}")

# Or using the sklearn function directly
print(f"Accuracy using sklearn.metrics.accuracy_score: {accuracy_score(y_test_cv, y_pred_cv):.4f}")

from sklearn.metrics import confusion_matrix

# Calculate the confusion matrix
cm = confusion_matrix(y_test_cv, y_pred_cv, labels=model_cv.classes_)

# Extract TP, TN, FP, FN (assuming 'positive' is the positive class and 'negative' is the negative class)
# The confusion_matrix output shape is [[TN, FP], [FN, TP]] for a binary classification

# Determine the index of 'negative' and 'positive' in model_cv.classes_
neg_idx = list(model_cv.classes_).index('negative')
pos_idx = list(model_cv.classes_).index('positive')

# Ensure correct assignment based on class order in model_cv.classes_
if neg_idx == 0 and pos_idx == 1: # Standard order: negative (0), positive (1)
    TN = cm[0, 0]
    FP = cm[0, 1]
    FN = cm[1, 0]
    TP = cm[1, 1]
elif neg_idx == 1 and pos_idx == 0: # Reversed order: positive (0), negative (1)
    TP = cm[0, 0]
    FN = cm[0, 1]
    FP = cm[1, 0]
    TN = cm[1, 1]
else:
    raise ValueError("Unexpected class order in confusion matrix.")

Accuracy = (TP + TN) / (TP + TN + FP + FN)

print(f"True Positives (TP): {TP}")
print(f"True Negatives (TN): {TN}")
print(f"False Positives (FP): {FP}")
print(f"False Negatives (FN): {FN}")
print(f"Accuracy from confusion matrix components: {Accuracy:.4f}")

from sklearn.metrics import accuracy_score

y_true = [1, 0, 1, 1, 0, 1]
y_pred = [1, 0, 0, 1, 0, 1]

acc = accuracy_score(y_true, y_pred)

print("Accuracy:", acc)

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

df = pd.read_csv("/content/IMDB_Dataset.csv.zip")  # your dataset

print(df.head())

df['sentiment'] = df['sentiment'].map({'positive': 1, 'negative': 0})

import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'http\S+|www\.\S+', '', text)
    text = re.sub(r'[^a-z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df['review'] = df['review'].apply(clean_text)

X_train, X_test, y_train, y_test = train_test_split(
    df['review'],
    df['sentiment'],
    test_size=0.2,
    random_state=42
)

vectorizer = TfidfVectorizer(stop_words='english')

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

model = MultinomialNB()
model.fit(X_train_vec, y_train)

y_pred = model.predict(X_test_vec)

from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer

# Ensure the vectorizer is consistent with the latest data split
vectorizer = TfidfVectorizer(stop_words='english')
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# Re-initialize and fit the MultinomialNB model to ensure it's using X_train_vec
model = MultinomialNB()
model.fit(X_train_vec, y_train)

y_pred = model.predict(X_test_vec)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import MultinomialNB

params = {
    'alpha': [0.01, 0.1, 0.5, 1, 2, 5]
}

grid = GridSearchCV(MultinomialNB(), params, cv=5, scoring='accuracy')
grid.fit(X_train_vec, y_train)

print("Best Alpha:", grid.best_params_)
print("Best Score:", grid.best_score_)

from sklearn.metrics import accuracy_score, classification_report, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Ensure y_pred is updated from the latest model (MultinomialNB) and X_test_vec
y_pred = model.predict(X_test_vec)

# Evaluate the Multinomial Naive Bayes model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy of Multinomial Naive Bayes model: {accuracy:.4f}")

print("\nClassification Report for Multinomial Naive Bayes:\n")
print(classification_report(y_test, y_pred))

# Visualize the confusion matrix for the Multinomial Naive Bayes model
fig, ax = plt.subplots(figsize=(8, 8))
ConfusionMatrixDisplay.from_estimator(model, X_test_vec, y_test, cmap=plt.cm.Blues, ax=ax)
plt.title('Confusion Matrix for Multinomial Naive Bayes')
plt.show()

from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import MultinomialNB

# Define the parameter grid to search
params = {
    'alpha': [0.01, 0.1, 0.5, 1, 2, 5]  # Smoothing parameter for MultinomialNB
}

# Initialize GridSearchCV
# cv=5 means 5-fold cross-validation
# scoring='accuracy' means the best model will be selected based on accuracy
grid_search = GridSearchCV(MultinomialNB(), params, cv=5, scoring='accuracy', verbose=1)

# Fit GridSearchCV to the training data
grid_search.fit(X_train_vec, y_train)

# Print the best parameters and the best score found
print("Best Alpha:", grid_search.best_params_)
print("Best Score:", grid_search.best_score_)

# You can access the best model directly
best_mnb_model = grid_search.best_estimator_

# Calculate training accuracy
training_accuracy = best_mnb_model.score(X_train_vec, y_train)

# Calculate testing accuracy (already computed, but re-calculate for consistency with the best model)
testing_accuracy = best_mnb_model.score(X_test_vec, y_test)

print(f"Training Accuracy (Best MNB Model): {training_accuracy:.4f}")
print(f"Testing Accuracy (Best MNB Model): {testing_accuracy:.4f}")

"""## Deploying the Model with Streamlit

Streamlit is an open-source Python library that allows you to create interactive web applications for machine learning and data science projects with minimal effort. Here's how you can create a simple Streamlit app to deploy your sentiment analysis model.

### 1. Save the Trained Model and Vectorizer

First, you need to save your trained `best_mnb_model` (from the GridSearchCV) and the `tfidf_vectorizer` (the one used for the MNB model) so that the Streamlit app can load them. We'll use `pickle` for this.
"""

import pickle
from sklearn.feature_extraction.text import TfidfVectorizer

# Assuming `best_mnb_model` and `vectorizer` (from TF-IDF used for MNB) are in your kernel state
# If you used CountVectorizer for MNB, replace `vectorizer` with `count_vectorizer`

# Save the best MNB model
with open('best_mnb_model.pkl', 'wb') as f:
    pickle.dump(best_mnb_model, f)

# Save the TF-IDF vectorizer (or CountVectorizer if that was used for MNB)
with open('tfidf_vectorizer.pkl', 'wb') as f:
    pickle.dump(vectorizer, f)

print("Model and Vectorizer saved successfully!")

pip install streamlit

import pickle

pickle.dump(model, open("model.pkl", "wb"))
pickle.dump(vectorizer, open("vectorizer.pkl", "wb"))

import streamlit as st
import pickle
import re

# Load model and vectorizer
model = pickle.load(open("model.pkl", "rb"))
vectorizer = pickle.load(open("vectorizer.pkl", "rb"))

# Text cleaning function
def clean_text(text):
    text = text.lower()
    text = re.sub(r'http\S+|www\.\S+', '', text)
    text = re.sub(r'[^a-z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

# App title
st.title("🎬 IMDB Sentiment Analysis App")

# User input
review = st.text_area("Enter Movie Review")

if st.button("Predict Sentiment"):
    cleaned = clean_text(review)

    # transform text
    vec = vectorizer.transform([cleaned])

    # prediction
    prediction = model.predict(vec)

    if prediction[0] == 1:
        st.success("😊 Positive Review")
    else:
        st.error("😡 Negative Review")

streamlit run app.py